_includes/banner.html
_includes/bigdropdown.html
_includes/top-bar.html
_sass/_custom.scss

Got it to work sort of hacking bootstrap. Not mobile friendly yet ..

first stab at large dropdown

---

_includes/banner.html
_includes/bigdropdown.html
_sass/_custom.scss

re-engineer banner area, aligning logo and dropdown using `row align-items-center` rather than some <br>

Tweak banner

---

_includes/ask-us.html
_includes/main-nav.html

just base content from old site, looks bad

add ask us modal content

---

_includes/footer.html

Fix search

---

_data/pagesnav.yml
_includes/breadcrumbs-page.html

this fixes breadcrumb issues by adding a parent to the pagesnav data

Fix breadcrumbs

---

content/open/index.html

Update Open Index

---

Rakefile
_config.yml

add a deploy command to simplify build with analytics

add basic rakefile test

---

_includes/ask-us.html
_includes/banner.html
_sass/_buttons.scss
_sass/_custom.scss
docs/chat-widgets.md

pull in updates originally created in `help-links` branch, updating Ask Us modal and button

Ask us update

---

_includes/bigdropdown-mobile.html
_includes/main-nav.html
_includes/searchnav.html
_sass/_index.scss

pull in redesign updates from `help-links` branch 
- mobile menu modal
- index search nav 
- clean up index sass

Nav redesign

---

_includes/js/spec_histphoto.js
_includes/js/spec_idahobio.js
content/special-collections/histphoto/index.html
content/special-collections/idahobio.html

update big tables, histphoto and idaho bio

Tables tweak

---

content/open/fellowship/call.md
content/open/fellowship/faq.md
content/open/fellowship/index.md

Reivising Think Open CFP and general Open pages
Hi Devin, I think I did this right but am not positive so hopefully this loops you in. I updated the Think Open pages and the CFP. Please feel free to edit/tweak, and/or launch if you think it looks good. Thank you!

Updating Think Open Pages

---

content/open/fellowship/call.md
content/open/fellowship/index.md
content/open/index.html

Updating various spots with new savings figures and the new CFP link. Was able to copy some buttons that were commented out from last time.

Updating with new CFP Link

---

content/about/hours.html
content/help/index.html

updates to ref hours / service

Ref updates

---

_includes/foot.html
_includes/head.html

add version tags to main.css and hours.js, seems to work (at least not break anything), should help with caching issues

try asset versions

---

content/datahub/index.md

create new data hub placeholder page at /datahub/

add data hub index

---

_layouts/redirect.html
content/liaison.md
docs/redirect.md

Liaison redirect

---

_includes/footer.html
content/about/directions.html
lib-apps/custom-footer.html

add final footer revision (to skip convoluted history of revisions with @owikle and @evanwill )

Footer final

---

_includes/js/spec_histphoto.html
assets/data/histphoto_full.csv
assets/data/histphoto_min.json
content/special-collections/histphoto/index.html

re @mshannon95 updated data for histphoto links

Histphoto update

---

_data/config_pagesnav.yml
_includes/feature/card.html
_includes/main-nav.html
content/about/updates.md
content/services/distance.md

re-add opening guide info, to new "updates" page

New opening guide

---

_includes/banner.html
_layouts/page.html
_sass/_base.scss

add very basic back to top button to page layout

Back to top2

---

_includes/footer.html

@owikle did we talk about this tweak to footer? I can't remember anything about it, but kind of like it. Let me know what you think.

Footer tweak

---

content/datahub/index.md

add zoom room to dh index page

add dh zoom room to dh index.md

---

_data/open_course_marking_faq.csv
content/open/course-marking.md

Added links and updated language on the course marking page

Course marking updates
